"""add risk_reward to signal_performance

Revision ID: 7ce832907fa1
Revises: 8350bb6d9a52
Create Date: 2026-03-30 00:35:53.905945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce832907fa1'
down_revision: Union[str, Sequence[str], None] = '8350bb6d9a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signal_performance', sa.Column('risk_reward', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_performance', 'risk_reward')
    # ### end Alembic commands ###
