"""add dedup constraints and FK cascade for session 6 tables

Revision ID: 8350bb6d9a52
Revises: cead421f4155
Create Date: 2026-03-29 00:35:22.200347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8350bb6d9a52'
down_revision: Union[str, Sequence[str], None] = 'cead421f4155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comex_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metal', sa.String(length=16), nullable=False),
    sa.Column('registered', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('stress_index', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comex_fetched', 'comex_inventory', ['fetched_at'], unique=False)
    op.create_index('ix_comex_metal', 'comex_inventory', ['metal'], unique=False)
    op.create_table('correlation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_a', sa.String(length=32), nullable=False),
    sa.Column('instrument_b', sa.String(length=32), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corr_calculated', 'correlation_snapshots', ['calculated_at'], unique=False)
    op.create_index('ix_corr_instruments', 'correlation_snapshots', ['instrument_a', 'instrument_b'], unique=False)
    op.create_table('geointel_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'category', name='uq_geointel_url_category')
    )
    op.create_index('ix_geointel_category', 'geointel_articles', ['category'], unique=False)
    op.create_index('ix_geointel_fetched', 'geointel_articles', ['fetched_at'], unique=False)
    op.create_table('seismic_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mag', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('depth_km', sa.Float(), nullable=False),
    sa.Column('place', sa.String(length=256), nullable=False),
    sa.Column('event_time', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_time', 'place', name='uq_seismic_event_time_place')
    )
    op.create_index('ix_seismic_fetched', 'seismic_events', ['fetched_at'], unique=False)
    op.create_index('ix_seismic_region', 'seismic_events', ['region'], unique=False)
    op.create_table('signal_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('pnl_pips', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sigperf_instrument', 'signal_performance', ['instrument'], unique=False)
    op.create_index('ix_sigperf_result', 'signal_performance', ['result'], unique=False)
    op.create_index('ix_sigperf_signal', 'signal_performance', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sigperf_signal', table_name='signal_performance')
    op.drop_index('ix_sigperf_result', table_name='signal_performance')
    op.drop_index('ix_sigperf_instrument', table_name='signal_performance')
    op.drop_table('signal_performance')
    op.drop_index('ix_seismic_region', table_name='seismic_events')
    op.drop_index('ix_seismic_fetched', table_name='seismic_events')
    op.drop_table('seismic_events')
    op.drop_index('ix_geointel_fetched', table_name='geointel_articles')
    op.drop_index('ix_geointel_category', table_name='geointel_articles')
    op.drop_table('geointel_articles')
    op.drop_index('ix_corr_instruments', table_name='correlation_snapshots')
    op.drop_index('ix_corr_calculated', table_name='correlation_snapshots')
    op.drop_table('correlation_snapshots')
    op.drop_index('ix_comex_metal', table_name='comex_inventory')
    op.drop_index('ix_comex_fetched', table_name='comex_inventory')
    op.drop_table('comex_inventory')
    # ### end Alembic commands ###
