"""initial schema

Revision ID: c71bd0f625ab
Revises: 
Create Date: 2026-03-26 08:09:59.530931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71bd0f625ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_index('ix_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('forecast', sa.String(length=32), nullable=True),
    sa.Column('previous', sa.String(length=32), nullable=True),
    sa.Column('actual', sa.String(length=32), nullable=True),
    sa.Column('hours_away', sa.Float(), nullable=True),
    sa.Column('affected_instruments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_date', 'calendar_events', ['date'], unique=False)
    op.create_index('ix_calendar_impact', 'calendar_events', ['impact'], unique=False)
    op.create_table('cot_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('market', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('change_oi', sa.Integer(), nullable=False),
    sa.Column('spec_long', sa.Integer(), nullable=False),
    sa.Column('spec_short', sa.Integer(), nullable=False),
    sa.Column('spec_net', sa.Integer(), nullable=False),
    sa.Column('comm_long', sa.Integer(), nullable=False),
    sa.Column('comm_short', sa.Integer(), nullable=False),
    sa.Column('comm_net', sa.Integer(), nullable=False),
    sa.Column('nonrept_long', sa.Integer(), nullable=False),
    sa.Column('nonrept_short', sa.Integer(), nullable=False),
    sa.Column('nonrept_net', sa.Integer(), nullable=False),
    sa.Column('change_spec_net', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'report_type', 'date', name='uq_cot_sym_rpt_date')
    )
    op.create_index('ix_cot_date', 'cot_positions', ['date'], unique=False)
    op.create_index('ix_cot_report_type', 'cot_positions', ['report_type'], unique=False)
    op.create_index('ix_cot_symbol', 'cot_positions', ['symbol'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('indicator_key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=16), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fundamental_key', 'fundamentals', ['indicator_key'], unique=False)
    op.create_index('ix_fundamental_updated', 'fundamentals', ['updated_at'], unique=False)
    op.create_table('instruments',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('class', sa.String(length=8), nullable=False),
    sa.Column('session', sa.String(length=64), nullable=False),
    sa.Column('cot_market', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('macro_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('vix_price', sa.Float(), nullable=True),
    sa.Column('vix_regime', sa.String(length=16), nullable=True),
    sa.Column('dollar_smile', sa.String(length=16), nullable=True),
    sa.Column('usd_bias', sa.String(length=32), nullable=True),
    sa.Column('fear_greed', sa.Float(), nullable=True),
    sa.Column('news_sentiment', sa.Text(), nullable=True),
    sa.Column('yield_curve', sa.Float(), nullable=True),
    sa.Column('conflicts', sa.Text(), nullable=True),
    sa.Column('full_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_macro_generated', 'macro_snapshots', ['generated_at'], unique=False)
    op.create_table('prices_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['instrument'], ['instruments.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument', 'date', name='uq_price_daily_inst_date')
    )
    op.create_index('ix_price_daily_date', 'prices_daily', ['date'], unique=False)
    op.create_index('ix_price_daily_instrument', 'prices_daily', ['instrument'], unique=False)
    op.create_table('prices_intraday',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['instrument'], ['instruments.key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument', 'timestamp', 'timeframe', name='uq_price_intraday')
    )
    op.create_index('ix_price_intraday_instrument', 'prices_intraday', ['instrument'], unique=False)
    op.create_index('ix_price_intraday_ts', 'prices_intraday', ['timestamp'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timeframe_bias', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('target_1', sa.Float(), nullable=True),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('rr_t1', sa.Float(), nullable=True),
    sa.Column('rr_t2', sa.Float(), nullable=True),
    sa.Column('entry_weight', sa.Integer(), nullable=True),
    sa.Column('t1_weight', sa.Integer(), nullable=True),
    sa.Column('sl_type', sa.String(length=16), nullable=True),
    sa.Column('at_level_now', sa.Boolean(), nullable=True),
    sa.Column('vix_regime', sa.String(length=16), nullable=True),
    sa.Column('pos_size', sa.String(length=16), nullable=True),
    sa.Column('score_details', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument'], ['instruments.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_generated', 'signals', ['generated_at'], unique=False)
    op.create_index('ix_signal_grade', 'signals', ['grade'], unique=False)
    op.create_index('ix_signal_instrument', 'signals', ['instrument'], unique=False)
    op.create_index('ix_signal_score', 'signals', ['score'], unique=False)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('pnl_pips', sa.Float(), nullable=True),
    sa.Column('pnl_rr', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_entry_date', 'backtest_results', ['entry_date'], unique=False)
    op.create_index('ix_backtest_instrument', 'backtest_results', ['instrument'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backtest_instrument', table_name='backtest_results')
    op.drop_index('ix_backtest_entry_date', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('ix_signal_score', table_name='signals')
    op.drop_index('ix_signal_instrument', table_name='signals')
    op.drop_index('ix_signal_grade', table_name='signals')
    op.drop_index('ix_signal_generated', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_price_intraday_ts', table_name='prices_intraday')
    op.drop_index('ix_price_intraday_instrument', table_name='prices_intraday')
    op.drop_table('prices_intraday')
    op.drop_index('ix_price_daily_instrument', table_name='prices_daily')
    op.drop_index('ix_price_daily_date', table_name='prices_daily')
    op.drop_table('prices_daily')
    op.drop_index('ix_macro_generated', table_name='macro_snapshots')
    op.drop_table('macro_snapshots')
    op.drop_table('instruments')
    op.drop_index('ix_fundamental_updated', table_name='fundamentals')
    op.drop_index('ix_fundamental_key', table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index('ix_cot_symbol', table_name='cot_positions')
    op.drop_index('ix_cot_report_type', table_name='cot_positions')
    op.drop_index('ix_cot_date', table_name='cot_positions')
    op.drop_table('cot_positions')
    op.drop_index('ix_calendar_impact', table_name='calendar_events')
    op.drop_index('ix_calendar_date', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_audit_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_event_type', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
