"""add bot tables

Revision ID: cead421f4155
Revises: c71bd0f625ab
Create Date: 2026-03-26 23:47:17.984325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cead421f4155'
down_revision: Union[str, Sequence[str], None] = 'c71bd0f625ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('broker_mode', sa.String(length=16), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('max_daily_trades', sa.Integer(), nullable=False),
    sa.Column('risk_pct', sa.Float(), nullable=False),
    sa.Column('min_grade', sa.String(length=4), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('kill_switch_active', sa.Boolean(), nullable=True),
    sa.Column('kill_switch_reason', sa.Text(), nullable=True),
    sa.Column('kill_switch_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('tv_payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_signal_instrument', 'bot_signals', ['instrument'], unique=False)
    op.create_index('ix_bot_signal_received', 'bot_signals', ['received_at'], unique=False)
    op.create_index('ix_bot_signal_status', 'bot_signals', ['status'], unique=False)
    op.create_table('bot_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_signal_id', sa.Integer(), nullable=True),
    sa.Column('broker_position_id', sa.String(length=64), nullable=True),
    sa.Column('instrument', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=False),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('lot_tier', sa.String(length=16), nullable=False),
    sa.Column('vix_regime', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('t1_hit', sa.Boolean(), nullable=True),
    sa.Column('t1_closed_pct', sa.Float(), nullable=True),
    sa.Column('candles_since_entry', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('pnl_pips', sa.Float(), nullable=True),
    sa.Column('pnl_usd', sa.Float(), nullable=True),
    sa.Column('pnl_rr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bot_signal_id'], ['bot_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_pos_instrument', 'bot_positions', ['instrument'], unique=False)
    op.create_index('ix_bot_pos_opened', 'bot_positions', ['opened_at'], unique=False)
    op.create_index('ix_bot_pos_status', 'bot_positions', ['status'], unique=False)
    op.create_table('bot_trade_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['bot_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_log_event', 'bot_trade_log', ['event_type'], unique=False)
    op.create_index('ix_trade_log_position', 'bot_trade_log', ['position_id'], unique=False)
    op.create_index('ix_trade_log_ts', 'bot_trade_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_log_ts', table_name='bot_trade_log')
    op.drop_index('ix_trade_log_position', table_name='bot_trade_log')
    op.drop_index('ix_trade_log_event', table_name='bot_trade_log')
    op.drop_table('bot_trade_log')
    op.drop_index('ix_bot_pos_status', table_name='bot_positions')
    op.drop_index('ix_bot_pos_opened', table_name='bot_positions')
    op.drop_index('ix_bot_pos_instrument', table_name='bot_positions')
    op.drop_table('bot_positions')
    op.drop_index('ix_bot_signal_status', table_name='bot_signals')
    op.drop_index('ix_bot_signal_received', table_name='bot_signals')
    op.drop_index('ix_bot_signal_instrument', table_name='bot_signals')
    op.drop_table('bot_signals')
    op.drop_table('bot_config')
    # ### end Alembic commands ###
